### ISSUE TITLE
SteamGameServer_Init call failed on built game

### ISSUE THREAD

**Issue by Lawrence-Abadier** [rlabrecque/Steamworks.NET-GameServerTest#1]
Hi,

Building this project with the appropriate dlls (steamclient.dll/tier0_s.dll/vstdlib_s.dll) fails to init the gameserver. I tried being logged in/out but it always fails. I put the dlls in unity before building under x86 folder, I also tried moving the dlls under the .exe directory but no luck. However, it succeeds to init gameserver within Unity.

Thank you,

**Comment by rlabrecque** [comment]
Do you have a steam_appid.txt next to the exe? That's required for game servers.

**Comment by Lawrence-Abadier** [comment]
EDIT: so this launched gameserver while logged into steam for the built version, but not while logged out.**

**Comment by rlabrecque** [comment]
Where were your steamclient.dll and it's dependencies when you tried? They should be next to the .exe IIRC.

**Comment by Lawrence-Abadier** [comment]
So I finally got it work with the following:

Under plugins folder I had steam_api.dll, and csteamworks.dll

Next to exe have the steam_api.dll, steamclient.dll, tier0_s.dll, vstdlib_s.dll, and steam_appid.txt.

Having the trio under the plugins folder always failed, and having steam_api.dll under the plugins folder did nothing. This was not working for me initially but with the addition to the appid it finally works.

Thank you for sticking this out with me!

**Comment by skoozeblood** [comment]
Getting this then out of memory, any ideas? On an Ubuntu 23.04 VPS.
